silent unzip

diff --git a/scripts/tmpl/get.kob_email_verification_service.io.tmpl b/scripts/tmpl/get.kob_email_verification_service.io.tmpl
--- a/scripts/tmpl/get.kob_email_verification_service.io.tmpl
+++ b/scripts/tmpl/get.kob_email_verification_service.io.tmpl
@@ -9,6 +9,9 @@ echo "Downloading necessary files..."
 curl -sL --location --progress-bar "${KOB_SERVICE}/${KOB_NAMESPACE}/KOB-email-verification/dist/dist/kob-email-latest.zip" > $HOME/kob-email.zip
 [[ "$?" != "0" ]] && echo "Something went wrong" && rm -rf $HOME/KOB-email-verification-service && exit 0
 echo "Unpacking files...."
-unzip $HOME/kob-email.zip -d $HOME/KOB-email-verification-service
-[[ "$?" == "0" ]] && echo "Success"
+unzip -q $HOME/kob-email.zip -d $HOME/KOB-email-verification-service
+if [[ "$?" == "0" ]]; then
+    echo "Success"
+else
+    echo "Failed unpacking files. Try again later."
 [[ -f $HOME/kob-email.zip ]] && rm $HOME/kob-email.zip
